#Vertretungsplan profile
#Mon Mar 02 13:24:39 CET 2026
profile.Fabus.name=Fabi
profile.Fabus.password=
profile.Fabus.username=siep_fab
profile.Fefe.name=Fefe
profile.Fefe.password=
profile.Fefe.username=weil_fel
profile.Jannik.name=J
profile.Jannik.password=
profile.Jannik.username=Lang_jan1
profile.Moritz.name=Mork
profile.Moritz.password=
profile.Moritz.username=wint_mor
profile.a.name=a
profile.a.password=
profile.a.username=bock_jak
profiles=Jannik,Fabus,Moritz,Fefe,a
